2024-03-14 12:44:00,046 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-14 12:44:00,081 - root - INFO - Baseline(
  (conv1): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv5): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1))
  (conv6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1))
  (output_conv): Conv2d(256, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
2024-03-14 13:37:10,835 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-14 13:37:10,869 - root - INFO - Baseline(
  (conv1): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv5): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1))
  (conv6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1))
  (output_conv): Conv2d(256, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
2024-03-14 13:42:05,980 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-14 13:42:06,017 - root - INFO - Baseline(
  (conv1): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv5): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1))
  (conv6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1))
  (output_conv): Conv2d(256, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
2024-03-14 13:57:24,557 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-14 13:57:24,590 - root - INFO - Baseline(
  (conv1): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv5): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1))
  (conv6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1))
  (output_conv): Conv2d(256, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
2024-03-14 14:05:56,309 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-14 14:05:56,345 - root - INFO - Baseline(
  (conv1): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv5): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1))
  (conv6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1))
  (output_conv): Conv2d(256, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
2024-03-14 14:05:58,132 - root - INFO - Data tensor shape: torch.Size([16384, 5, 1, 32, 32]), used for creating the dataloader.
2024-03-14 14:11:18,210 - root - INFO - Data tensor shape: torch.Size([32768, 5, 1, 32, 32]), used for creating the dataloader.
2024-03-14 14:17:03,250 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-14 14:17:03,285 - root - INFO - Baseline(
  (conv1): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv5): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1))
  (conv6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1))
  (output_conv): Conv2d(256, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
2024-03-14 14:17:05,042 - root - INFO - Data tensor shape: torch.Size([16384, 5, 1, 32, 32]), used for creating the dataloader.
2024-03-14 14:22:18,378 - root - INFO - Generator can be trained from epoch 1 onwards
2024-03-14 14:22:22,273 - root - INFO - Data tensor shape: torch.Size([32768, 5, 1, 32, 32]), used for creating the dataloader.
2024-03-14 14:38:45,131 - root - INFO - Data tensor shape: torch.Size([49152, 5, 1, 32, 32]), used for creating the dataloader.
2024-03-14 14:51:11,318 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-14 14:51:11,352 - root - INFO - Baseline(
  (conv1): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv5): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1))
  (conv6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1))
  (output_conv): Conv2d(256, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
2024-03-14 15:09:46,511 - root - INFO - Data tensor shape: torch.Size([65536, 5, 1, 32, 32]), used for creating the dataloader.
Epoch 00110: reducing learning rate of group 0 to 1.0000e-03.
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 183, in _fit
    for batch in self.test_dataloader:
AttributeError: 'TrainingPredictor' object has no attribute 'test_dataloader'
2024-03-15 08:11:51,631 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-15 08:11:51,661 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(1, 1), stride=(1, 1))
  (convs): ModuleList(
    (0-29): 30 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py:251: UserWarning: Error detected in ReluBackward0. Traceback of forward call that caused the error:
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 136, in _fit
    predicted_metric = self.predictor.model(self.__get_initial_config(batch))
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/predictors/Baseline.py", line 164, in forward
    x = self.relu(x)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 101, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1471, in relu
    result = torch.relu(input)
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 138, in _fit
    errP.backward()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128, 32, 32, 32]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
2024-03-15 08:14:18,964 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-15 08:14:18,997 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(1, 1), stride=(1, 1))
  (convs): ModuleList(
    (0-29): 30 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py:251: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 136, in _fit
    predicted_metric = self.predictor.model(self.__get_initial_config(batch))
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/predictors/Baseline.py", line 162, in forward
    x = toroidal_Conv2d(x, conv, padding=1)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/predictors/utils/toroidal.py", line 9, in toroidal_Conv2d
    x = conv2d(x)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 138, in _fit
    errP.backward()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'ConvolutionBackward0' returned nan values in its 0th output.
2024-03-15 08:15:14,110 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-15 08:15:14,140 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-29): 30 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py:251: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 136, in _fit
    predicted_metric = self.predictor.model(self.__get_initial_config(batch))
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/predictors/Baseline.py", line 162, in forward
    identity = x
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/predictors/utils/toroidal.py", line 9, in toroidal_Conv2d
    x = conv2d(x)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 138, in _fit
    errP.backward()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'ConvolutionBackward0' returned nan values in its 1th output.
2024-03-15 08:15:54,732 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-15 08:15:54,761 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-29): 30 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
Epoch 00007: reducing learning rate of group 0 to 1.0000e-03.
Epoch 00012: reducing learning rate of group 0 to 1.0000e-04.
Epoch 00017: reducing learning rate of group 0 to 1.0000e-05.
Epoch 00022: reducing learning rate of group 0 to 1.0000e-06.
Epoch 00027: reducing learning rate of group 0 to 1.0000e-07.
Epoch 00032: reducing learning rate of group 0 to 1.0000e-08.
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 183, in _fit
    for batch in self.test_dataloader:
AttributeError: 'TrainingPredictor' object has no attribute 'test_dataloader'
2024-03-16 08:07:45,053 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-16 08:07:45,082 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (convs): ModuleList(
    (0-29): 30 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 136, in _fit
    predicted_metric = self.predictor.model(self.__get_initial_config(batch))
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/predictors/Baseline.py", line 170, in forward
    out += identity  # Element-wise addition for skip connection
RuntimeError: The size of tensor a (38) must match the size of tensor b (34) at non-singleton dimension 3
2024-03-16 08:09:00,331 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-16 08:09:00,361 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-29): 30 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py:251: UserWarning: Error detected in ReluBackward0. Traceback of forward call that caused the error:
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 136, in _fit
    predicted_metric = self.predictor.model(self.__get_initial_config(batch))
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/predictors/Baseline.py", line 166, in forward
    out = toroidal_Conv2d(x, conv, padding=1)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 101, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1471, in relu
    result = torch.relu(input)
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 138, in _fit
    errP.backward()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128, 32, 32, 32]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
2024-03-16 08:12:07,274 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-16 08:12:07,307 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-29): 30 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
Epoch 00132: reducing learning rate of group 0 to 1.0000e-03.
Epoch 00137: reducing learning rate of group 0 to 1.0000e-04.
Epoch 00142: reducing learning rate of group 0 to 1.0000e-05.
Epoch 00147: reducing learning rate of group 0 to 1.0000e-06.
Epoch 00152: reducing learning rate of group 0 to 1.0000e-07.
Epoch 00157: reducing learning rate of group 0 to 1.0000e-08.
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 183, in _fit
    for batch in self.test_dataloader:
AttributeError: 'TrainingPredictor' object has no attribute 'test_dataloader'
2024-03-17 02:13:58,476 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-17 02:13:58,512 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-39): 40 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py:251: UserWarning: Error detected in MseLossBackward0. Traceback of forward call that caused the error:
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 137, in _fit
    errP = self.predictor.criterion(predicted_metric, self.__get_metric_config(batch, self.metric_type))
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 535, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 3329, in mse_loss
    return torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 138, in _fit
    errP.backward()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'MseLossBackward0' returned nan values in its 0th output.
2024-03-17 02:15:12,674 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-17 02:15:12,704 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-39): 40 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py:251: UserWarning: Error detected in MseLossBackward0. Traceback of forward call that caused the error:
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 137, in _fit
    errP = self.predictor.criterion(predicted_metric, self.__get_metric_config(batch, self.metric_type))
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 535, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 3329, in mse_loss
    return torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 138, in _fit
    errP.backward()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'MseLossBackward0' returned nan values in its 0th output.
2024-03-17 02:20:05,316 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-17 02:20:05,355 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-39): 40 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (bn_layers): ModuleList(
    (0-39): 40 x BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py:251: UserWarning: Error detected in CudnnBatchNormBackward0. Traceback of forward call that caused the error:
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 136, in _fit
    predicted_metric = self.predictor.model(self.__get_initial_config(batch))
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/predictors/Baseline.py", line 164, in forward
    out = bn(out)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2478, in batch_norm
    return torch.batch_norm(
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 108, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 138, in _fit
    errP.backward()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'CudnnBatchNormBackward0' returned nan values in its 0th output.
2024-03-17 02:36:15,671 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-17 02:36:15,712 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-39): 40 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (bn_layers): ModuleList(
    (0-39): 40 x BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
Epoch 00018: reducing learning rate of group 0 to 1.0000e-04.
Epoch 00025: reducing learning rate of group 0 to 1.0000e-05.
Epoch 00033: reducing learning rate of group 0 to 1.0000e-06.
Epoch 00038: reducing learning rate of group 0 to 1.0000e-07.
Epoch 00043: reducing learning rate of group 0 to 1.0000e-08.
2024-03-17 12:04:53,847 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-17 12:04:53,882 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-39): 40 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (bn_layers): ModuleList(
    (0-39): 40 x BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
2024-03-17 12:12:58,568 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-17 12:12:58,608 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-39): 40 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (bn_layers): ModuleList(
    (0-39): 40 x BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
2024-03-17 12:13:11,636 - root - INFO - Training started at 17/03/2024 12:13:11
2024-03-17 12:14:28,758 - root - INFO - Logging configuration loaded from /home/bletchkey/ASGNTC/config/logging.json
2024-03-17 12:14:28,795 - root - INFO - Baseline_v4(
  (in_conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
  (convs): ModuleList(
    (0-39): 40 x Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (bn_layers): ModuleList(
    (0-39): 40 x BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (out_conv): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
  (relu): ReLU()
)
2024-03-17 12:14:41,705 - root - INFO - Training started at 17/03/2024 12:14:41
2024-03-17 12:25:57,463 - root - INFO - Training started at 17/03/2024 12:25:57
2024-03-17 17:43:02,911 - root - INFO - Training started at 17/03/2024 17:43:02
2024-03-17 18:34:18,825 - root - INFO - Training started at 17/03/2024 18:34:18
2024-03-17 18:42:16,286 - root - INFO - Training started at 17/03/2024 18:42:16
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 107, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 130, in _fit
    warmup_scheduler = optim.lr_scheduler.LambdaLR(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 217, in __init__
    super().__init__(optimizer, last_epoch, verbose)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 78, in __init__
    self._initial_step()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 84, in _initial_step
    self.step()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 147, in step
    values = self.get_lr()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 264, in get_lr
    return [base_lr * lmbda(self.last_epoch)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 264, in <listcomp>
    return [base_lr * lmbda(self.last_epoch)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 133, in <lambda>
    min(1.0, step / constants.warmup_total_steps) * (constants.warmup_target_lr - constants.warmup_initial_lr) \
AttributeError: module 'src.gol_adv_sys.utils.constants' has no attribute 'warmup_initial_lr'
2024-03-17 18:44:11,228 - root - INFO - Training started at 17/03/2024 18:44:11
2024-03-17 18:57:00,250 - root - INFO - Training started at 17/03/2024 18:57:00
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    RETCODE = main()
  File "main.py", line 92, in main
    train_predictor()
  File "main.py", line 84, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 107, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 166, in _fit
    train_loss /= len(self.dataloader["train"])
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 147, in step
    values = self.get_lr()
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 264, in get_lr
    return [base_lr * lmbda(self.last_epoch)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 264, in <listcomp>
    return [base_lr * lmbda(self.last_epoch)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 135, in <lambda>
    
IndexError: list index out of range
2024-03-17 19:03:54,629 - root - INFO - Training started at 17/03/2024 19:03:54
Epoch 00031: reducing learning rate of group 0 to 1.0000e-02.
Epoch 00036: reducing learning rate of group 0 to 1.0000e-03.
Epoch 00041: reducing learning rate of group 0 to 1.0000e-04.
Epoch 00046: reducing learning rate of group 0 to 1.0000e-05.
Epoch 00051: reducing learning rate of group 0 to 1.0000e-06.
Epoch 00056: reducing learning rate of group 0 to 1.0000e-07.
Epoch 00061: reducing learning rate of group 0 to 1.0000e-08.
2024-03-18 08:44:30,191 - root - INFO - Training started at 18/03/2024 08:44:30
Epoch 00011: reducing learning rate of group 0 to 1.0000e-02.
Epoch 00016: reducing learning rate of group 0 to 1.0000e-03.
Epoch 00021: reducing learning rate of group 0 to 1.0000e-04.
Epoch 00026: reducing learning rate of group 0 to 1.0000e-05.
Epoch 00031: reducing learning rate of group 0 to 1.0000e-06.
Epoch 00036: reducing learning rate of group 0 to 1.0000e-07.
Epoch 00041: reducing learning rate of group 0 to 1.0000e-08.
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from src.gol_adv_sys.Playground import Playground
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 8, in <module>
    from src.gol_adv_sys.utils.constants import constants as constants
ImportError: cannot import name 'constants' from 'src.gol_adv_sys.utils.constants' (/home/bletchkey/ASGNTC/src/gol_adv_sys/utils/constants.py)
Period: 2
Antiperiod: 144
Initial living cells: 512
Final living cells: 66
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    RETCODE = main()
  File "main.py", line 97, in main
    playground()
  File "main.py", line 75, in playground
    data, metadata = pg.get_config_idx(0)
AttributeError: 'Playground' object has no attribute 'get_config_idx'
Period: 2
Antiperiod: 426
Initial living cells: 512
Final living cells: 30
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    RETCODE = main()
  File "main.py", line 97, in main
    playground()
  File "main.py", line 75, in playground
    data, metadata = pg.get_config_id(0)
TypeError: cannot unpack non-iterable NoneType object
Period: 2
Antiperiod: 643
Initial living cells: 512
Final living cells: 44
Traceback (most recent call last):
  File "main.py", line 105, in <module>
    RETCODE = main()
  File "main.py", line 96, in main
    playground()
  File "main.py", line 75, in playground
    data, metadata = pg.get_config_id(0)
TypeError: cannot unpack non-iterable NoneType object
Period: 2
Antiperiod: 831
Initial living cells: 512
Final living cells: 28
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    RETCODE = main()
  File "main.py", line 97, in main
    playground()
  File "main.py", line 75, in playground
    data = pg.get_config_id(0)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 84, in get_config_id
    raise ValueError(f"Could not find the data for id {id}")
ValueError: Could not find the data for id 0
Period: 2
Antiperiod: 1302
Initial living cells: 512
Final living cells: 28
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    RETCODE = main()
  File "main.py", line 97, in main
    playground()
  File "main.py", line 75, in playground
    data = pg.get_config_id(1000)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 81, in get_config_id
    return self.__create_data(data, meta)
TypeError: __create_data() takes 2 positional arguments but 3 were given
Period: 2
Antiperiod: 690
Initial living cells: 512
Final living cells: 33
id: 1000
n_cells_init: 3
n_cells_final: 0
period: 1
antiperiod: 0
initial_config: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
final_config: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
easy_metric: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
medium_metric: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
hard_metric: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
Period: 2
Antiperiod: 692
Initial living cells: 512
Final living cells: 21
id: 131072
n_cells_init: 512
n_cells_final: 43
period: 2
antiperiod: 2051
initial_config: tensor([[[0., 1., 0.,  ..., 0., 0., 1.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         [1., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 1., 0.],
         [1., 0., 1.,  ..., 0., 0., 1.],
         [0., 1., 0.,  ..., 0., 1., 1.]]], device='cuda:0')
final_config: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
easy_metric: tensor([[[0.4613, 0.7581, 0.5434,  ..., 0.2071, 0.5542, 0.7188],
         [0.4963, 0.0492, 0.6463,  ..., 0.2475, 0.3508, 0.2331],
         [0.5028, 0.2514, 0.5626,  ..., 0.3943, 0.2393, 0.7238],
         ...,
         [0.0274, 0.2311, 0.3526,  ..., 0.5035, 0.3557, 0.1779],
         [0.7966, 0.7316, 0.4676,  ..., 0.7814, 0.3888, 0.1994],
         [0.0640, 0.5615, 0.2986,  ..., 0.0258, 0.5059, 0.0433]]],
       device='cuda:0')
medium_metric: tensor([[[0.5292, 0.5398, 0.4991,  ..., 0.1361, 0.4049, 0.5290],
         [0.4918, 0.1326, 0.6107,  ..., 0.2360, 0.3935, 0.2627],
         [0.3153, 0.2636, 0.4995,  ..., 0.4622, 0.2818, 0.6021],
         ...,
         [0.1243, 0.2650, 0.4255,  ..., 0.4875, 0.4250, 0.2050],
         [0.6481, 0.5675, 0.4338,  ..., 0.6123, 0.3803, 0.2801],
         [0.1477, 0.4546, 0.4331,  ..., 0.1059, 0.3406, 0.1345]]],
       device='cuda:0')
hard_metric: tensor([[[0.1685, 0.0834, 0.0475,  ..., 0.1023, 0.0599, 0.1283],
         [0.0689, 0.1240, 0.0598,  ..., 0.0610, 0.1520, 0.0710],
         [0.1536, 0.0962, 0.0607,  ..., 0.0703, 0.1673, 0.0898],
         ...,
         [0.0648, 0.0605, 0.0592,  ..., 0.1255, 0.0813, 0.0725],
         [0.1025, 0.0504, 0.0352,  ..., 0.1125, 0.0997, 0.1137],
         [0.1359, 0.1054, 0.0406,  ..., 0.1160, 0.0741, 0.1006]]],
       device='cuda:0')
Period: 2
Antiperiod: 776
Initial living cells: 512
Final living cells: 54
id: 131072
n_cells_init: 512
n_cells_final: 43
period: 2
antiperiod: 2051
initial_config: tensor([[[0., 1., 0.,  ..., 0., 0., 1.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         [1., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 1., 0.],
         [1., 0., 1.,  ..., 0., 0., 1.],
         [0., 1., 0.,  ..., 0., 1., 1.]]], device='cuda:0')
final_config: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
easy_metric: tensor([[[0.4613, 0.7581, 0.5434,  ..., 0.2071, 0.5542, 0.7188],
         [0.4963, 0.0492, 0.6463,  ..., 0.2475, 0.3508, 0.2331],
         [0.5028, 0.2514, 0.5626,  ..., 0.3943, 0.2393, 0.7238],
         ...,
         [0.0274, 0.2311, 0.3526,  ..., 0.5035, 0.3557, 0.1779],
         [0.7966, 0.7316, 0.4676,  ..., 0.7814, 0.3888, 0.1994],
         [0.0640, 0.5615, 0.2986,  ..., 0.0258, 0.5059, 0.0433]]],
       device='cuda:0')
medium_metric: tensor([[[0.5292, 0.5398, 0.4991,  ..., 0.1361, 0.4049, 0.5290],
         [0.4918, 0.1326, 0.6107,  ..., 0.2360, 0.3935, 0.2627],
         [0.3153, 0.2636, 0.4995,  ..., 0.4622, 0.2818, 0.6021],
         ...,
         [0.1243, 0.2650, 0.4255,  ..., 0.4875, 0.4250, 0.2050],
         [0.6481, 0.5675, 0.4338,  ..., 0.6123, 0.3803, 0.2801],
         [0.1477, 0.4546, 0.4331,  ..., 0.1059, 0.3406, 0.1345]]],
       device='cuda:0')
hard_metric: tensor([[[0.1685, 0.0834, 0.0475,  ..., 0.1023, 0.0599, 0.1283],
         [0.0689, 0.1240, 0.0598,  ..., 0.0610, 0.1520, 0.0710],
         [0.1536, 0.0962, 0.0607,  ..., 0.0703, 0.1673, 0.0898],
         ...,
         [0.0648, 0.0605, 0.0592,  ..., 0.1255, 0.0813, 0.0725],
         [0.1025, 0.0504, 0.0352,  ..., 0.1125, 0.0997, 0.1137],
         [0.1359, 0.1054, 0.0406,  ..., 0.1160, 0.0741, 0.1006]]],
       device='cuda:0')
Period: 2
Antiperiod: 737
Initial living cells: 512
Final living cells: 39
id: 131072
n_cells_init: 512
n_cells_final: 43
period: 2
antiperiod: 2051
initial_config: tensor([[[0., 1., 0.,  ..., 0., 0., 1.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         [1., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 1., 0.],
         [1., 0., 1.,  ..., 0., 0., 1.],
         [0., 1., 0.,  ..., 0., 1., 1.]]], device='cuda:0')
final_config: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
easy_metric: tensor([[[0.4613, 0.7581, 0.5434,  ..., 0.2071, 0.5542, 0.7188],
         [0.4963, 0.0492, 0.6463,  ..., 0.2475, 0.3508, 0.2331],
         [0.5028, 0.2514, 0.5626,  ..., 0.3943, 0.2393, 0.7238],
         ...,
         [0.0274, 0.2311, 0.3526,  ..., 0.5035, 0.3557, 0.1779],
         [0.7966, 0.7316, 0.4676,  ..., 0.7814, 0.3888, 0.1994],
         [0.0640, 0.5615, 0.2986,  ..., 0.0258, 0.5059, 0.0433]]],
       device='cuda:0')
  0.9818977117538452
  1.8598904880870474e-33
medium_metric: tensor([[[0.5292, 0.5398, 0.4991,  ..., 0.1361, 0.4049, 0.5290],
         [0.4918, 0.1326, 0.6107,  ..., 0.2360, 0.3935, 0.2627],
         [0.3153, 0.2636, 0.4995,  ..., 0.4622, 0.2818, 0.6021],
         ...,
         [0.1243, 0.2650, 0.4255,  ..., 0.4875, 0.4250, 0.2050],
         [0.6481, 0.5675, 0.4338,  ..., 0.6123, 0.3803, 0.2801],
         [0.1477, 0.4546, 0.4331,  ..., 0.1059, 0.3406, 0.1345]]],
       device='cuda:0')
  0.9065380096435547
  2.1579461350503784e-17
hard_metric: tensor([[[0.1685, 0.0834, 0.0475,  ..., 0.1023, 0.0599, 0.1283],
         [0.0689, 0.1240, 0.0598,  ..., 0.0610, 0.1520, 0.0710],
         [0.1536, 0.0962, 0.0607,  ..., 0.0703, 0.1673, 0.0898],
         ...,
         [0.0648, 0.0605, 0.0592,  ..., 0.1255, 0.0813, 0.0725],
         [0.1025, 0.0504, 0.0352,  ..., 0.1125, 0.0997, 0.1137],
         [0.1359, 0.1054, 0.0406,  ..., 0.1160, 0.0741, 0.1006]]],
       device='cuda:0')
  0.422981858253479
  0.02702675200998783
2024-03-20 02:32:48,107 - root - INFO - Training started at 20/03/2024 02:32:48
Period: 2
Antiperiod: 216
Initial living cells: 512
Final living cells: 23
id: 131072
n_cells_init: 512
n_cells_final: 43
period: 2
antiperiod: 2051
initial_config: tensor([[[0., 1., 0.,  ..., 0., 0., 1.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         [1., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 1., 0.],
         [1., 0., 1.,  ..., 0., 0., 1.],
         [0., 1., 0.,  ..., 0., 1., 1.]]], device='cuda:0')
final_config: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
easy_metric: tensor([[[0.4613, 0.7581, 0.5434,  ..., 0.2071, 0.5542, 0.7188],
         [0.4963, 0.0492, 0.6463,  ..., 0.2475, 0.3508, 0.2331],
         [0.5028, 0.2514, 0.5626,  ..., 0.3943, 0.2393, 0.7238],
         ...,
         [0.0274, 0.2311, 0.3526,  ..., 0.5035, 0.3557, 0.1779],
         [0.7966, 0.7316, 0.4676,  ..., 0.7814, 0.3888, 0.1994],
         [0.0640, 0.5615, 0.2986,  ..., 0.0258, 0.5059, 0.0433]]],
       device='cuda:0')
  0.9818977117538452
  1.8598904880870474e-33
medium_metric: tensor([[[0.5292, 0.5398, 0.4991,  ..., 0.1361, 0.4049, 0.5290],
         [0.4918, 0.1326, 0.6107,  ..., 0.2360, 0.3935, 0.2627],
         [0.3153, 0.2636, 0.4995,  ..., 0.4622, 0.2818, 0.6021],
         ...,
         [0.1243, 0.2650, 0.4255,  ..., 0.4875, 0.4250, 0.2050],
         [0.6481, 0.5675, 0.4338,  ..., 0.6123, 0.3803, 0.2801],
         [0.1477, 0.4546, 0.4331,  ..., 0.1059, 0.3406, 0.1345]]],
       device='cuda:0')
  0.9065380096435547
  2.1579461350503784e-17
hard_metric: tensor([[[0.1685, 0.0834, 0.0475,  ..., 0.1023, 0.0599, 0.1283],
         [0.0689, 0.1240, 0.0598,  ..., 0.0610, 0.1520, 0.0710],
         [0.1536, 0.0962, 0.0607,  ..., 0.0703, 0.1673, 0.0898],
         ...,
         [0.0648, 0.0605, 0.0592,  ..., 0.1255, 0.0813, 0.0725],
         [0.1025, 0.0504, 0.0352,  ..., 0.1125, 0.0997, 0.1137],
         [0.1359, 0.1054, 0.0406,  ..., 0.1160, 0.0741, 0.1006]]],
       device='cuda:0')
  0.422981858253479
  0.02702675200998783
Traceback (most recent call last):
  File "main.py", line 111, in <module>
    RETCODE = main()
  File "main.py", line 103, in main
    playground()
  File "main.py", line 84, in playground
    pg.plot_antiperiods()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 93, in plot_antiperiods
    for id, antiperiod in zip(self.__dataset["train_meta"]["id"], self.__dataset["train_meta"]["antiperiod"]):
TypeError: list indices must be integers or slices, not str
Period: 1
Antiperiod: 208
Initial living cells: 512
Final living cells: 15
id: 131072
n_cells_init: 512
n_cells_final: 43
period: 2
antiperiod: 2051
initial_config: tensor([[[0., 1., 0.,  ..., 0., 0., 1.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         [1., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 1., 0.],
         [1., 0., 1.,  ..., 0., 0., 1.],
         [0., 1., 0.,  ..., 0., 1., 1.]]], device='cuda:0')
final_config: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
easy_metric: tensor([[[0.4613, 0.7581, 0.5434,  ..., 0.2071, 0.5542, 0.7188],
         [0.4963, 0.0492, 0.6463,  ..., 0.2475, 0.3508, 0.2331],
         [0.5028, 0.2514, 0.5626,  ..., 0.3943, 0.2393, 0.7238],
         ...,
         [0.0274, 0.2311, 0.3526,  ..., 0.5035, 0.3557, 0.1779],
         [0.7966, 0.7316, 0.4676,  ..., 0.7814, 0.3888, 0.1994],
         [0.0640, 0.5615, 0.2986,  ..., 0.0258, 0.5059, 0.0433]]],
       device='cuda:0')
  0.9818977117538452
  1.8598904880870474e-33
medium_metric: tensor([[[0.5292, 0.5398, 0.4991,  ..., 0.1361, 0.4049, 0.5290],
         [0.4918, 0.1326, 0.6107,  ..., 0.2360, 0.3935, 0.2627],
         [0.3153, 0.2636, 0.4995,  ..., 0.4622, 0.2818, 0.6021],
         ...,
         [0.1243, 0.2650, 0.4255,  ..., 0.4875, 0.4250, 0.2050],
         [0.6481, 0.5675, 0.4338,  ..., 0.6123, 0.3803, 0.2801],
         [0.1477, 0.4546, 0.4331,  ..., 0.1059, 0.3406, 0.1345]]],
       device='cuda:0')
  0.9065380096435547
  2.1579461350503784e-17
hard_metric: tensor([[[0.1685, 0.0834, 0.0475,  ..., 0.1023, 0.0599, 0.1283],
         [0.0689, 0.1240, 0.0598,  ..., 0.0610, 0.1520, 0.0710],
         [0.1536, 0.0962, 0.0607,  ..., 0.0703, 0.1673, 0.0898],
         ...,
         [0.0648, 0.0605, 0.0592,  ..., 0.1255, 0.0813, 0.0725],
         [0.1025, 0.0504, 0.0352,  ..., 0.1125, 0.0997, 0.1137],
         [0.1359, 0.1054, 0.0406,  ..., 0.1160, 0.0741, 0.1006]]],
       device='cuda:0')
  0.422981858253479
  0.02702675200998783
2024-03-20 02:55:46,925 - root - INFO - Training started at 20/03/2024 02:55:46
Epoch 00044: reducing learning rate of group 0 to 1.0000e-02.
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from src.gol_adv_sys.Playground import Playground
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 126
    plt.savefig(f"record_{record["id"]}.png")
                                  ^
SyntaxError: invalid syntax
Period: 2
Antiperiod: 224
Initial living cells: 512
Final living cells: 50
  0.9818977117538452
  1.8598904880870474e-33
  0.9065380096435547
  2.1579461350503784e-17
  0.422981858253479
  0.02702675200998783
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    RETCODE = main()
  File "main.py", line 108, in main
    playground()
  File "main.py", line 82, in playground
    pg.plot_record(data)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 109, in plot_record
    axs[0, 0].imshow(record["initial_config"])
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5663, in imshow
    im.set_data(X)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/image.py", line 697, in set_data
    self._A = cbook.safe_masked_invalid(A, copy=True)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 719, in safe_masked_invalid
    x = np.array(x, subok=True, copy=copy)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/_tensor.py", line 1030, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Period: 2
Antiperiod: 203
Initial living cells: 512
Final living cells: 35
  0.9818977117538452
  1.8598904880870474e-33
  0.9065380096435547
  2.1579461350503784e-17
  0.422981858253479
  0.02702675200998783
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    RETCODE = main()
  File "main.py", line 108, in main
    playground()
  File "main.py", line 84, in playground
    pg.load_predictor("predictor_medium_metric.pt")
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 92, in load_predictor
    raise ValueError(f"Model {name} does not exist")
ValueError: Model predictor_medium_metric.pt does not exist
Period: 2
Antiperiod: 2389
Initial living cells: 512
Final living cells: 33
  0.9818977117538452
  1.8598904880870474e-33
  0.9065380096435547
  2.1579461350503784e-17
  0.422981858253479
  0.02702675200998783
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    RETCODE = main()
  File "main.py", line 108, in main
    playground()
  File "main.py", line 85, in playground
    pred = pg.predict(data["initial_config"])
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 103, in predict
    return self.__predictor["model"](config)
TypeError: 'dict' object is not callable
Period: 2
Antiperiod: 791
Initial living cells: 512
Final living cells: 28
EASY MAX: 0.9818977117538452
EASY MIN: 1.8598904880870474e-33
MEDIUM MAX: 0.9065380096435547
MEDIUM MIN: 2.1579461350503784e-17
HARD MAX: 0.422981858253479
HARD MIN: 0.02702675200998783
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    RETCODE = main()
  File "main.py", line 114, in main
    playground()
  File "main.py", line 91, in playground
    pred = pg.predict(data["initial_config"])
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 103, in predict
    return self.__predictor["model"](config)
TypeError: 'dict' object is not callable
Period: 2
Antiperiod: 411
Initial living cells: 512
Final living cells: 37
EASY MAX: 0.9818977117538452
EASY MIN: 1.8598904880870474e-33
MEDIUM MAX: 0.9065380096435547
MEDIUM MIN: 2.1579461350503784e-17
HARD MAX: 0.422981858253479
HARD MIN: 0.02702675200998783
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    RETCODE = main()
  File "main.py", line 114, in main
    playground()
  File "main.py", line 91, in playground
    pred = pg.predict(data["initial_config"])
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 103, in predict
    self.__predictor["model"].eval()
AttributeError: 'dict' object has no attribute 'eval'
Period: 2
Antiperiod: 247
Initial living cells: 512
Final living cells: 45
EASY MAX: 0.9818977117538452
EASY MIN: 1.8598904880870474e-33
MEDIUM MAX: 0.9065380096435547
MEDIUM MIN: 2.1579461350503784e-17
HARD MAX: 0.422981858253479
HARD MIN: 0.02702675200998783
Period: 2
Antiperiod: 116
Initial living cells: 512
Final living cells: 31
EASY MAX: 0.9818977117538452
EASY MIN: 1.8598904880870474e-33
MEDIUM MAX: 0.9065380096435547
MEDIUM MIN: 2.1579461350503784e-17
HARD MAX: 0.422981858253479
HARD MIN: 0.02702675200998783
Period: 1
Antiperiod: 772
Initial living cells: 512
Final living cells: 17
EASY MAX: 0.9818977117538452
EASY MIN: 1.8598904880870474e-33
MEDIUM MAX: 0.9065380096435547
MEDIUM MIN: 2.1579461350503784e-17
HARD MAX: 0.422981858253479
HARD MIN: 0.02702675200998783
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    RETCODE = main()
  File "main.py", line 114, in main
    playground()
  File "main.py", line 88, in playground
    pg.plot_record(data)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 111, in plot_record
    gs = GridSpec(2, 5, figure=fig)
NameError: name 'GridSpec' is not defined
Period: 2
Antiperiod: 1184
Initial living cells: 512
Final living cells: 26
EASY MAX: 0.9818977117538452
EASY MIN: 1.8598904880870474e-33
MEDIUM MAX: 0.9065380096435547
MEDIUM MIN: 2.1579461350503784e-17
HARD MAX: 0.422981858253479
HARD MIN: 0.02702675200998783
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    RETCODE = main()
  File "main.py", line 114, in main
    playground()
  File "main.py", line 88, in playground
    pg.plot_record(data)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/Playground.py", line 111, in plot_record
    gs = GridSpec(2, 5, figure=fig)
NameError: name 'GridSpec' is not defined
Period: 2
Antiperiod: 982
Initial living cells: 512
Final living cells: 50
EASY MAX: 0.9818977117538452
EASY MIN: 1.8598904880870474e-33
MEDIUM MAX: 0.9065380096435547
MEDIUM MIN: 2.1579461350503784e-17
HARD MAX: 0.422981858253479
HARD MIN: 0.02702675200998783
Period: 1
Antiperiod: 279
Initial living cells: 512
Final living cells: 14
EASY MAX: 0.9818977117538452
EASY MIN: 1.8598904880870474e-33
MEDIUM MAX: 0.9065380096435547
MEDIUM MIN: 2.1579461350503784e-17
HARD MAX: 0.422981858253479
HARD MIN: 0.02702675200998783
